
package com.kasra.javaee.jax.ws.proxy;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "biography", targetNamespace = "http://ws.jax.javaee.kasra.com/", wsdlLocation = "http://localhost:8084//biography?wsdl")
public class Biography
    extends Service
{

    private final static URL BIOGRAPHY_WSDL_LOCATION;
    private final static WebServiceException BIOGRAPHY_EXCEPTION;
    private final static QName BIOGRAPHY_QNAME = new QName("http://ws.jax.javaee.kasra.com/", "biography");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8084//biography?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BIOGRAPHY_WSDL_LOCATION = url;
        BIOGRAPHY_EXCEPTION = e;
    }

    public Biography() {
        super(__getWsdlLocation(), BIOGRAPHY_QNAME);
    }

    public Biography(WebServiceFeature... features) {
        super(__getWsdlLocation(), BIOGRAPHY_QNAME, features);
    }

    public Biography(URL wsdlLocation) {
        super(wsdlLocation, BIOGRAPHY_QNAME);
    }

    public Biography(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BIOGRAPHY_QNAME, features);
    }

    public Biography(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Biography(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServerWS
     */
    @WebEndpoint(name = "ServerWSPort")
    public ServerWS getServerWSPort() {
        return super.getPort(new QName("http://ws.jax.javaee.kasra.com/", "ServerWSPort"), ServerWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServerWS
     */
    @WebEndpoint(name = "ServerWSPort")
    public ServerWS getServerWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.jax.javaee.kasra.com/", "ServerWSPort"), ServerWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BIOGRAPHY_EXCEPTION!= null) {
            throw BIOGRAPHY_EXCEPTION;
        }
        return BIOGRAPHY_WSDL_LOCATION;
    }

}
