
package com.kasra.javaee.jax.ws.proxy;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServerWS", targetNamespace = "http://ws.jax.javaee.kasra.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface ServerWS {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.jax.javaee.kasra.com/ServerWS/nameRequest", output = "http://ws.jax.javaee.kasra.com/ServerWS/nameResponse")
    public String name(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

}
